-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  call_id text NOT NULL UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  call_started_at timestamp with time zone,
  representative text NOT NULL DEFAULT 'Layla (AI)'::text,
  practice text NOT NULL DEFAULT 'Awaaz Labs Cardiology'::text,
  patient_acct text,
  assigned_doctor text NOT NULL DEFAULT 'Dr. Adeel Rahman'::text,
  language text,
  contact_number text,
  whatsapp_suitable boolean,
  first_name text,
  full_legal_name text,
  dob date,
  gender text,
  mailing_address text,
  callback_number text,
  email text,
  reason text,
  appointment_text text,
  appointment_at timestamp with time zone,
  patient_status text,
  patient_status_unverified boolean DEFAULT false,
  insurance_status text DEFAULT 'pending'::text,
  payer_name text,
  member_id text,
  group_number text,
  plan_type text,
  payer_id text,
  customer_service_number text,
  provider_name text,
  npi text,
  tax_id text,
  cpt_codes text,
  date_of_service date,
  patient_is_subscriber boolean,
  subscriber_name text,
  subscriber_dob date,
  subscriber_relationship text,
  subscriber_employer text,
  has_secondary boolean,
  secondary_payer text,
  secondary_member_id text,
  primary_plan text,
  plan_change_this_year boolean,
  plan_change_details text,
  referring_provider text,
  prior_auth boolean,
  prior_auth_number text,
  seen_other_provider text,
  notes text,
  intake_method text DEFAULT 'voice'::text,
  form_status text DEFAULT 'not_sent'::text,
  source text DEFAULT 'voice'::text,
  needs_review boolean DEFAULT false,
  review_reasons ARRAY DEFAULT '{}'::text[],
  triage_flag text DEFAULT 'none'::text,
  transfer_initiated boolean DEFAULT false,
  confirmation_status text DEFAULT 'pending'::text,
  confirmation_channel text,
  transcript text,
  call_summary text,
  recording_url text,
  raw_payload jsonb,
  CONSTRAINT bookings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.message_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  call_id text,
  booking_id uuid,
  purpose text,
  channel text,
  provider text,
  to_number text,
  body text,
  status text,
  provider_message_id text,
  error text,
  CONSTRAINT message_log_pkey PRIMARY KEY (id),
  CONSTRAINT message_log_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);